import org.apache.tools.ant.filters.ReplaceTokens

plugins {
    id 'java'
    id "com.gradleup.shadow" version "9.0.0-beta6"
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.16"
}

version = '1.2.0'
def minecraft = '1.21.4'

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

repositories {
    mavenCentral()
    mavenLocal()

    // Paper
    maven { url 'https://repo.papermc.io/repository/maven-public/' }

    // Skript
    maven { url 'https://repo.skriptlang.org/releases' }

    // JitPack
    maven { url 'https://jitpack.io' }
}

dependencies {
    // Paper
    paperweight.paperDevBundle("${minecraft}-R0.1-SNAPSHOT")

    // Skript
    compileOnly(group: 'com.github.SkriptLang', name: 'Skript', version: '2.10.0') {
        transitive = false
    }

    // SkBee
    compileOnly("com.github.ShaneBeee:SkBee:3.8.0")

    // bStats
    implementation(group: 'org.bstats', name: 'bstats-bukkit', version: '3.0.2')
}

jar {
    archiveFileName = project.name + "-" + project.version + "-" + minecraft + ".jar"
}

shadowJar {
    archiveFileName = project.name + "-" + project.version + "-" + minecraft + ".jar"
    relocate("org.bstats", "com.shanebeestudios.nms.metrics")
}

build {
    dependsOn(shadowJar)
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.compilerArgs.add("-Xlint:unchecked")
            options.compilerArgs.add("-Xlint:deprecation")
        }
    }
}

processResources {
    filesNotMatching("**/*.png") {
        filter ReplaceTokens, tokens: ["version": project.version]
        filter ReplaceTokens, tokens: ["minecraft": minecraft]
    }
}

// Run task to build jar to another spot
tasks.register('server', Copy) {
    from shadowJar
    // Change this to wherever you want your jar to build
    into '/Users/ShaneBee/Desktop/Server/Skript/1-21-4/plugins'
}

