test "SkNMS - Custom Biome":
	set {_biome} to register new biome:
		id: "my_biomes:blue_forest"
		has_precipitation: true
		temperature: 2.0
		downfall: 1.0
		effects:
			fog_color: rgb(240,227,159)
			water_color: rgb(159,240,215)
			water_fog_color: rgb(159,240,215)
			sky_color: rgb(159,226,240)
			foliage_color: yellow
			grass_color: blue
			grass_color_modifier: "swamp"
	assert {_biome} is set with "Should have registered"
	set {_test} to "my_biomes:blue_forest" parsed as biome
	assert {_test} is set with "The biome should parsed"
	delete {_test}

	set {_biome2} to register new biome:
		id: "my_biomes:burnt_forest"
		has_precipitation: true
		temperature: 0.7
		downfall: 0.8
		effects:
			fog_color: 12638463
			water_color: 9614049
			water_fog_color: 329011
			sky_color: 7972607
			grass_color: 12295008
			foliage_color: 7435380
			particle: particle option of white_ash with probability 1
	assert {_biome2} is set with "Should have registered"
	set {_test} to "my_biomes:burnt_forest" parsed as biome
	assert {_test} is set with "The biome should parsed"
	delete {_test}

	set {_biome3} to register new biome:
		id: "my_biomes:cool_forest"
		has_precipitation: true
		temperature: 0.7
		downfall: 0.8
		effects:
			fog_color: 12638463
			water_color: 9614049
			water_fog_color: 329011
			sky_color: 7972607
			grass_color: 9617074
			foliage_color: 45188
			particle: particle option of block with data dirt[] with probability 0.003
	assert {_biome3} is set with "Should have registered"
	set {_test} to "my_biomes:cool_forest" parsed as biome
	assert {_test} is set with "The biome should parsed"
	delete {_test}

	set {_biome4} to register new biome:
		id: "my_biomes:colorful_coast"
		has_precipitation: true
		temperature: 0.7
		downfall: 0.8
		features:
			underground_ores:
				apply feature "minecraft:ore_dirt"
				apply feature "minecraft:ore_coal_upper"
				apply feature "minecraft:ore_coal_lower"
			vegetal_decoration:
				apply feature "minecraft:glow_lichen"
				apply feature "minecraft:patch_grass_savanna"
				apply feature "minecraft:patch_tall_grass_2"
				apply feature "minecraft:brown_mushroom_normal"
				apply feature "minecraft:red_mushroom_normal"
				apply feature "minecraft:patch_sugar_cane"
	assert {_biome4} is set with "Should have registered"
	set {_test} to "my_biomes:colorful_coast" parsed as biome
	assert {_test} is set with "The biome should parsed"
	delete {_test}
